/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.*;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Binh
 */
public class MainFrame extends javax.swing.JFrame {
    private LoginPanel loginPanel;
    private RegistrationPanel registrationPanel;
    private CalendarPanel calendarPanel;
    private ClassesPanel classesPanel;
    private EmailPanel emailPanel;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        this.menuPane.setVisible(false);
        this.titleJPanel.setVisible(false);
        
        // Adding a Login panel
        this.loginPanel = new LoginPanel();
        this.loginPanel.setSize(this.getSize());
        this.loginPanel.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED));
        this.mainJPanel.add(this.loginPanel);
        this.loginPanel.addLoginBtnActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // TODO check for correct username and password
                // if it is correct --> display menuPane and titleJpanle
                if (loginPanel.getEmail().length() != 0 && loginPanel.getPwd().length() != 0
                        && (loginPanel.getEmail().equals("student") && loginPanel.getPwd().equals("student")
                        || (loginPanel.getEmail().equals("prof") && loginPanel.getPwd().equals("prof")))) {
                    loginPanel.setVisible(false);
                    loginPanel.clearFields();
                    menuPane.setVisible(true);
                    titleJPanel.setVisible(true);
                } else {
                    // Display an error message --> JOptionPane for now?
                    String errorMsg = "Your account was not found. Here are the possible issues:\n"
                            + "- Your account is not verified. Please check your personal email;\n"
                            + "- Wrong email and/or password. Please try again;";
                    JOptionPane.showMessageDialog(null, errorMsg, "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
        this.loginPanel.addCreateAccMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                loginPanel.setVisible(false);
                registrationPanel.setVisible(true);
            }
            @Override
            public void mousePressed(MouseEvent e) {}
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
            @Override
            public void mouseExited(MouseEvent e) {}
        });
        
        // Adding a Registration panel
        this.registrationPanel = new RegistrationPanel();
        this.registrationPanel.setSize(this.getSize());
        this.mainJPanel.add(this.registrationPanel);
        // TODO add subscriber to registration
        
        // Adding a Calendar panel
        this.calendarPanel = new CalendarPanel();
        this.calendarPanel.setSize(this.panelForCalendar.getSize());
        this.panelForCalendar.add(this.calendarPanel);
        
        // Adding a Classes panel
        this.classesPanel = new ClassesPanel();
        this.classesPanel.setSize(this.panelForClasses.getSize());
        this.panelForClasses.add(this.classesPanel);
        this.classesPanel.addAddClassBtnActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.out.println("Clicked");
                classesPanel.setVisible(false);
                // TODO switch to AddClassPanel (as student)
                
            }
        });
        
        this.emailPanel = new EmailPanel();
        this.emailPanel.setSize(this.menuPane.getSize());
        this.emailPanel.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED));
        // this.mainJPanel.add(this.emailPanel);
        
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        titleJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        menuPane = new javax.swing.JTabbedPane();
        panelForCalendar = new javax.swing.JPanel();
        panelForClasses = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deadline");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));

        mainJPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        titleJPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("DeadLine");

        logoutBtn.setBackground(new java.awt.Color(102, 102, 102));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPane.setToolTipText("");
        menuPane.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        panelForCalendar.setLayout(new java.awt.BorderLayout());
        menuPane.addTab("Calendar", panelForCalendar);

        panelForClasses.setLayout(new java.awt.BorderLayout());
        menuPane.addTab("Classes", panelForClasses);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        menuPane.addTab("Profile", jPanel1);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPane)
                .addContainerGap())
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addComponent(titleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.loginPanel.setVisible(true);
        this.menuPane.setVisible(false);
        this.titleJPanel.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JTabbedPane menuPane;
    private javax.swing.JPanel panelForCalendar;
    private javax.swing.JPanel panelForClasses;
    private javax.swing.JPanel titleJPanel;
    // End of variables declaration//GEN-END:variables
}